# Generated by Django 3.1.5 on 2021-01-10 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_state', '0002_auto_20201026_0025'),
        ('meme_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeme',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_state.game'),
        ),
    ]
