# Generated by Django 3.1.2 on 2020-10-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_state', '0002_auto_20201025_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.IntegerField(choices=[(1, 'Creating Game Room'), (2, 'Waiting for Players'), (3, 'Forging Memes'), (4, 'Judging Memes'), (5, 'Presenting Winners')], default='Creating Game Room', help_text='The current game state, as also reflected in the game clients.'),
        ),
    ]
