# Generated by Django 3.1.2 on 2021-03-25 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_state', '0001_initial'),
        ('data_mine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memetemplatetogamethrough',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_state.game'),
        ),
        migrations.AddField(
            model_name='memetemplatetogamethrough',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_mine.memetemplate'),
        ),
        migrations.AddConstraint(
            model_name='memetemplatetogamethrough',
            constraint=models.UniqueConstraint(fields=('game', 'template'), name='no_duplicate_templates_for_a_game'),
        ),
    ]
