# Generated by Django 3.1.2 on 2020-10-25 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_mine", "0003_auto_20201026_0007"),
        ("game_state", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memetemplatetogamethrough",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game_state.app"
            ),
        ),
        migrations.AddField(
            model_name="memetemplatetogamethrough",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="data_mine.memetemplate"
            ),
        ),
        migrations.AddConstraint(
            model_name="memetemplatetogamethrough",
            constraint=models.UniqueConstraint(
                fields=("app", "template"), name="no_duplicate_templates_for_a_game"
            ),
        ),
    ]
