# Generated by Django 3.1 on 2020-08-16 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("data_mine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMeme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="The URL to the user meme image stored on our server.",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="data_mine.memetemplate",
                    ),
                ),
            ],
        ),
    ]
