# Generated by Django 3.1.2 on 2020-10-24 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_state', '0001_initial'),
        ('meme_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermeme',
            options={'verbose_name': 'User Meme', 'verbose_name_plural': 'User Memes'},
        ),
        migrations.AddField(
            model_name='usermeme',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_state.player'),
        ),
        migrations.AlterField(
            model_name='usermeme',
            name='url',
            field=models.CharField(db_index=True, help_text='The URL to the user meme image stored on our server.', max_length=512, null=True, unique=True, verbose_name='URL'),
        ),
    ]
