# Generated by Django 3.1 on 2020-08-16 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MemeTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        db_index=True,
                        help_text="The URL to the template image stored on our server.",
                        max_length=512,
                        unique=True,
                    ),
                ),
                (
                    "added_timestamp",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp in which the template was data-mined or otherwise added.",
                    ),
                ),
                (
                    "likes",
                    models.IntegerField(
                        default=0,
                        help_text="The number of times this template has been liked.",
                    ),
                ),
                (
                    "dislikes",
                    models.IntegerField(
                        default=0,
                        help_text="The number of times this template has been disliked.",
                    ),
                ),
                (
                    "throw_back_probability",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        help_text=(
                            "How likely is it that, when selected, the meme template will simply be ignored and a new "
                            "one selected? The default value is 0.0 (0%). This field is dynamically determined,"
                        ),
                        max_digits=16,
                        validators=[
                            django.core.validators.MaxValueValidator(1.0),
                            django.core.validators.MinValueValidator(0.0),
                        ],
                    ),
                ),
                (
                    "staleness_routine_override",
                    models.DateTimeField(
                        blank=True,
                        help_text=(
                            "If set to the date in which the override was last added, the throw_back_probability will "
                            "be frozen and not calculated by the staleness algorithm."
                        ),
                        null=True,
                    ),
                ),
            ],
        ),
    ]
