# Generated by Django 3.1.2 on 2020-10-25 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game_state", "0001_initial"),
        ("data_mine", "0003_auto_20201025_1729"),
    ]

    operations = [
        migrations.AddField(
            model_name="memetemplatetogamethrough",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game_state.game"
            ),
        ),
        migrations.AddField(
            model_name="memetemplatetogamethrough",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="data_mine.memetemplate"
            ),
        ),
        migrations.AddConstraint(
            model_name="memetemplatetogamethrough",
            constraint=models.UniqueConstraint(
                fields=("game", "order"), name="game_template_order_unique"
            ),
        ),
    ]
