# Generated by Django 3.1.2 on 2020-10-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_mine', '0005_auto_20201025_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memetemplatetogamethrough',
            name='order',
            field=models.PositiveSmallIntegerField(help_text='The order-by field per-game.'),
        ),
    ]
